In [1]:
import torch

In [2]:
from torch.nn.utils.rnn import pad_sequence
model = RawNet2()

In [3]:
batch = torch.randn(size=(1, 34356))
batch2 = torch.randn(size=(1, 53446))

In [4]:
a = pad_sequence([batch.reshape(-1), batch2.reshape(-1)], batch_first=True)

In [7]:
model(a)["logits"].argmax(-1)

tensor([1, 0])

In [3]:
a = torch.ones(size=(300,))

In [8]:
torch.nn.functional.pad(a, (0, 200)).shape

torch.Size([500])

In [12]:
from pathlib import Path
from datetime import datetime

save_dir = Path("saved/")
exper_name = "name"
run_id = datetime.now().strftime(r"%m%d_%H%M%S")
_save_dir = str(save_dir / "models" / exper_name / run_id)
_log_dir = str(save_dir / "log" / exper_name / run_id)

# make directory for saving checkpoints and log.

Path(_save_dir).mkdir(parents=True, exist_ok=True)
Path(_log_dir).mkdir(parents=True, exist_ok=True)

In [14]:
import torch 
ckpt = torch.load("/Users/bayesian_monster/Downloads/RawNetE122.pth", map_location="cpu")

OrderedDict([('first_conv.low_hz_',
              tensor([[   0.0000],
                      [  76.8632],
                      [ 181.7941],
                      [ 304.4029],
                      [ 440.6732],
                      [ 590.0258],
                      [ 765.1478],
                      [ 963.6710],
                      [1188.7220],
                      [1443.8458],
                      [1733.0610],
                      [2081.4309],
                      [2453.1040],
                      [2874.4424],
                      [3352.0830],
                      [3893.5488],
                      [4507.3691],
                      [5203.2119],
                      [5992.0381],
                      [6886.2725]])),
             ('first_conv.band_hz_',
              tensor([[ 76.8747],
                      [ 89.3713],
                      [103.5433],
                      [119.0579],
                      [136.5472],
                      [157.1839],
                    